### ISSUE TITLE
problem in KickFinal defining the QTR Sensors array.

### ISSUE THREAD

**Issue by lacedemonian** [mcterse/bmcc-robotics#1]
Arduino: 1.6.3 (Windows 7), Board: "Arduino Uno"

KickFinal.ino:12:40: error: 'A8' was not declared in this scope

KickFinal.ino:12:44: error: 'A9' was not declared in this scope

KickFinal.ino:12:48: error: 'A10' was not declared in this scope

KickFinal.ino:12:53: error: 'A11' was not declared in this scope

KickFinal.ino:12:58: error: 'A12' was not declared in this scope

KickFinal.ino:12:63: error: 'A13' was not declared in this scope

KickFinal.ino:12:68: error: 'A14' was not declared in this scope

KickFinal.ino:12:73: error: 'A15' was not declared in this scope

**Comment by lacedemonian** [comment]
I just noticed this is also for SpiralFinal

I presume that these are the ports used for the QTR sensors, but arduino seems to think they are variables.

**Comment by lacedemonian** [comment]
Issue resolved.

You forgot the quote marks.

**Comment by mcterse** [comment]
those variables are considered undeclared if you set the arduino ide as
arduino uno and not arduino mega. The uno doesn't have all those ports.
There shouldnt be any quote marks in the object declaration.

On Sat, Mar 19, 2016 at 1:40 PM, Elijah Robinson <notifications@github.com>
wrote:

> Closed #1 <https://github.com/mcterse/bmcc-robotics/issues/1>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mcterse/bmcc-robotics/issues/1#event-595941793>
>



-- 
______________
Pavel Javornik
